// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: remote_cloud_control.proto
#ifndef GRPC_remote_5fcloud_5fcontrol_2eproto__INCLUDED
#define GRPC_remote_5fcloud_5fcontrol_2eproto__INCLUDED

#include "remote_cloud_control.pb.h"

#include <grpc++/impl/internal_stub.h>
#include <grpc++/impl/rpc_method.h>
#include <grpc++/impl/service_type.h>
#include <grpc++/async_unary_call.h>
#include <grpc++/status.h>
#include <grpc++/stream.h>

namespace grpc {
class CompletionQueue;
class ChannelInterface;
class RpcService;
class ServerContext;
}  // namespace grpc

namespace rtp_plus_plus {

class RemoteCallControlService GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status call(::grpc::ClientContext* context, const ::rtp_plus_plus::CalleeInfo& request, ::rtp_plus_plus::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rtp_plus_plus::Response>> Asynccall(::grpc::ClientContext* context, const ::rtp_plus_plus::CalleeInfo& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rtp_plus_plus::Response>>(AsynccallRaw(context, request, cq, tag));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rtp_plus_plus::Response>* AsynccallRaw(::grpc::ClientContext* context, const ::rtp_plus_plus::CalleeInfo& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface, public ::grpc::InternalStub {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status call(::grpc::ClientContext* context, const ::rtp_plus_plus::CalleeInfo& request, ::rtp_plus_plus::Response* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rtp_plus_plus::Response>> Asynccall(::grpc::ClientContext* context, const ::rtp_plus_plus::CalleeInfo& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rtp_plus_plus::Response>>(AsynccallRaw(context, request, cq, tag));
    }

   private:
    ::grpc::ClientAsyncResponseReader< ::rtp_plus_plus::Response>* AsynccallRaw(::grpc::ClientContext* context, const ::rtp_plus_plus::CalleeInfo& request, ::grpc::CompletionQueue* cq, void* tag) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_call_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);

  class Service : public ::grpc::SynchronousService {
   public:
    Service() : service_(nullptr) {}
    virtual ~Service();
    virtual ::grpc::Status call(::grpc::ServerContext* context, const ::rtp_plus_plus::CalleeInfo* request, ::rtp_plus_plus::Response* response);
    ::grpc::RpcService* service() GRPC_OVERRIDE GRPC_FINAL;
   private:
    ::grpc::RpcService* service_;
  };
  class AsyncService GRPC_FINAL : public ::grpc::AsynchronousService {
   public:
    explicit AsyncService(::grpc::CompletionQueue* cq);
    ~AsyncService() {};
    void Requestcall(::grpc::ServerContext* context, ::rtp_plus_plus::CalleeInfo* request, ::grpc::ServerAsyncResponseWriter< ::rtp_plus_plus::Response>* response, ::grpc::CompletionQueue* cq, void *tag);
  };
};

}  // namespace rtp_plus_plus


#endif  // GRPC_remote_5fcloud_5fcontrol_2eproto__INCLUDED
